apiVersion: v1
kind: Service
metadata:
  name: helloweb
  labels:
    app: hello
  namespace: "${#alphanumerical(execution['trigger']['user'])}-${#alphanumerical(execution['trigger']['type'])}-${#alphanumerical(execution['startTime'])}"
spec:
  selector:
    app: hello
    tier: web
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  type: ClusterIP

